image:
  repository: teeboss/adetola-portfolio
  pullPolicy: IfNotPresent
  tag: v6
service:
  type: NodePort
  port: 80
  nodePort: 30080
serviceAccount:
  create: false
ingress:
  enabled: false
  annotations: {}
  hosts:
    - host: chart-example.local
      paths:
        - path: /
          pathType: ImplementationSpecific
  tls: []
autoscaling:
  enabled: false
  minReplicas: 1
  maxReplicas: 5
  targetCPUUtilizationPercentage: 80
  
